/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sudoku_solver_og;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Priyansh Dubey
 */
public class HomeFrame extends javax.swing.JFrame {
    Sudoku_file game;
    

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame(Sudoku_file game) {
        this.game = game ;
        this.getContentPane().setBackground(new Color(0x4a0404)); 
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((dim.width/2)-231, (dim.height/2)-345);
        ImageIcon logo = new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\SUDOKU_Solver_OG\\src\\Resources\\game.png");
        setIconImage(logo.getImage());
      
       
      
        initComponents();
        
        // Set background image
        ImageIcon backgroundImg = new ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\SUDOKU_Solver_OG\\src\\Resources\\finalmy.png");
        JLabel background = new JLabel(backgroundImg);
        background.setBounds(0, 0, backgroundImg.getIconWidth(), backgroundImg.getIconHeight());
        gameBanner.add(background);

        // Make the panel transparent
        gameBanner.setOpaque(false);
    }
    
    private void getStart (Sudoku_file game){
        game.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameBanner = new javax.swing.JPanel();
        play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        play.setBackground(new java.awt.Color(255, 255, 102));
        play.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        play.setForeground(new java.awt.Color(51, 0, 0));
        play.setText("PLAY");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameBannerLayout = new javax.swing.GroupLayout(gameBanner);
        gameBanner.setLayout(gameBannerLayout);
        gameBannerLayout.setHorizontalGroup(
            gameBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBannerLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(play)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        gameBannerLayout.setVerticalGroup(
            gameBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameBannerLayout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addComponent(play)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        getStart(this.game); 
        
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameBanner;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
